# Generated by Django 5.0.2 on 2024-09-04 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booktb3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=20)),
                ('usename', models.CharField(max_length=20)),
                ('bmobile', models.IntegerField()),
                ('baddress', models.CharField(max_length=20)),
                ('service', models.CharField(max_length=20)),
                ('serviceman', models.CharField(max_length=20)),
                ('contact', models.IntegerField()),
                ('date', models.DateField()),
                ('days', models.IntegerField()),
                ('subamount', models.IntegerField(blank=True, null=True)),
                ('billamount', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed')], default='pending', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='emtb3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('message', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='regtb3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('contact', models.IntegerField()),
                ('date', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('image', models.FileField(upload_to='pictures')),
                ('address', models.CharField(max_length=30)),
                ('option', models.CharField(max_length=20)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='servicetb3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('service', models.CharField(max_length=20)),
                ('idd', models.CharField(max_length=20)),
                ('image', models.FileField(upload_to='pictures')),
                ('is_complete', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.regtb3')),
            ],
        ),
    ]
