# Generated by Django 5.0.2 on 2024-09-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktb3',
            name='cusername',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
